const data = [
"You’re strong.",
"Aside from food. You’re my favorite.",
"You bring out the best in other people.",
"When you say, “I meant to do that,” I totally believe you.",
"When you’re not afraid to be yourself is when you’re most incredible.",
"You’re more fun than a ball pit filled with candy. (And seriously, what could be more fun than that?)",
"Your hair looks stunning.",
"Someone is getting through something hard right now because you’ve got their back.",
"If you were a box of crayons, you'd be the giant name-brand one with the built-in sharpener.",
"You're really something special.",
"Jokes are funnier when you tell them.",
"You always know how to find that silver lining.",
"You're a candle in the darkness.",
"Being around you is like a happy little vacation.",
"You're more fun than bubble wrap.",
"You're like a breath of fresh air.",
"You're someone's reason to smile.",
"How do you keep being so funny and making everyone laugh?",
"You have impeccable manners.",
"I like your style.",
"You're strong.",
"Is that your picture next to "charming" in the dictionary?",
"Your kindness is a balm to all who encounter it.",
"You are brave.",
"You are beautiful on the inside and outside.",
"You have the courage of your convictions.",
"You're a great listener.",
"You were cool way before hipsters were cool.",
"That thing you don't like about yourself is what makes you really interesting.",
"You're inspiring.",
"You're so thoughtful.",
"When you make up your mind, nothing stands in your way.",
"You seem to really know who you are.",
"You're a smart cookie.",
"Your perspective is refreshing.",
"Your ability to recall random factoids at just the right times is impressive.",
"When you say, "I meant to do that," I totally believe you.",
"You have the best ideas.",
"You're always learning new things and trying to better yourself. That's awesome.",
"If someone based an Internet meme on you, it would have impeccable grammar.",
"You could survive a zombie apocalypse.",
"When you make a mistake, you fix it.",
"You're great at figuring stuff out.",
"Your creative potential seems limitless.",
"I bet you do crossword puzzles in ink.",
"You have a good head on your shoulders.",
"Everyone gets knocked down sometimes; only people like you get back up again and keep going.",
"I am so proud of you, and I hope you are too!",
"You are making a difference.",
"You deserve a hug right now.",
"You're a great example to others.",
"Actions speak louder than words, and yours tell an incredible story.",
"You are glowing—and that's the least interesting thing about you, too.",
"You look great today.",
"Your eyes are breathtaking.",
"How is it that you always look so great, even if you're in ratty pajamas?",
"That color is perfect on you.",
"You smell really good.",
"You may dance like no one's watching, but everyone's watching because you're mesmerizing.",
"You have cute elbows. For real.",
"Your belly button is kind of adorable.",
"Your hair looks stunning.",
"Your voice is magnificent.",
"Your name suits you to a T.",
"You're irresistible when you blush.",
"Has anyone ever told you that you have great posture?",
"I absolutely love that shirt. It really brings out the color of your eyes.",
"Your hair looks so great today.",
"You have such a great sense of style.",
"You have such a great personality.",
"I really enjoy talking to you.",
"Your smile is contagious.",
"You have the best laugh.",
"You light up the room.",
"You have a great sense of humor.",
"If cartoon bluebirds were real, a couple of 'em would be sitting on your shoulders singing right now.",
"You're like sunshine on a rainy day.",
"You bring out the best in other people.",
"I bet you sweat glitter.",
"Colors seem brighter when you're around.",
"You're more fun than a ball pit filled with candy."
]


module.exports=data
